"""Stage the Dukascopy CSV + ImportDukaTicks_EA into MT5, compile, then run.

After the download finishes:
  1. Copy `data/duka/XAUUSD_*.csv` to <data>/MQL5/Files/duka/.
  2. Copy `scripts/ImportDukaTicks_EA.mq5` to <data>/MQL5/Experts/ImportDuka/.
  3. Compile it via MetaEditor64.exe /compile:.
  4. Generate an import .ini that runs the EA on any symbol for 1 day.
  5. Launch terminal64.exe /config:import.ini to fire the import.
  6. Wait for terminal to exit, log the imported tick count.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FOLDER = Path(
    r"C:\Users\nikof\AppData\Roaming\MetaQuotes\Terminal"
    r"\5FFA568149E88FCD5B44D926DCFEAA79"
)
TERMINAL_EXE = Path(r"C:\Program Files\RoboForex MT5 Terminal\terminal64.exe")
META_EDITOR = Path(r"C:\Program Files\RoboForex MT5 Terminal\MetaEditor64.exe")


def write_utf16(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-16")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, type=Path,
                    help="Path to the local Dukascopy tick CSV")
    ap.add_argument("--custom-name", default="XAUUSD.duk")
    args = ap.parse_args()

    if not args.csv.exists():
        print(f"[duka_import] CSV not found: {args.csv}")
        return 2

    # --- 1. Stage CSV ----------------------------------------------------
    csv_rel = Path("duka") / args.csv.name
    csv_dest = DATA_FOLDER / "MQL5" / "Files" / csv_rel
    csv_dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(args.csv, csv_dest)
    print(f"[duka_import] staged CSV -> {csv_dest} ({csv_dest.stat().st_size:,} bytes)")

    # --- 2. Stage EA source ----------------------------------------------
    ea_src = REPO_ROOT / "scripts" / "ImportDukaTicks_EA.mq5"
    ea_dest_dir = DATA_FOLDER / "MQL5" / "Experts" / "ImportDuka"
    ea_dest_dir.mkdir(parents=True, exist_ok=True)
    ea_dest = ea_dest_dir / ea_src.name
    shutil.copy2(ea_src, ea_dest)
    print(f"[duka_import] staged EA  -> {ea_dest}")

    # --- 3. Compile ------------------------------------------------------
    compile_log = ea_dest.with_suffix(".compile.log")
    rc = subprocess.call([
        str(META_EDITOR),
        f"/compile:{ea_dest}",
        f"/log:{compile_log}",
    ])
    print(f"[duka_import] MetaEditor compile rc={rc}")
    ex5_path = ea_dest.with_suffix(".ex5")
    if not ex5_path.exists():
        print(f"[duka_import] ERROR: {ex5_path} not produced")
        if compile_log.exists():
            print(compile_log.read_text(encoding="utf-16", errors="replace"))
        return 3
    print(f"[duka_import] compiled  -> {ex5_path}")

    # --- 4. Generate import .ini ----------------------------------------
    ini_path = DATA_FOLDER / "MQL5" / "Profiles" / "Tester" / "DukaImport.ini"
    ini_content = "\r\n".join([
        "; Dukascopy custom-symbol import, generated by scripts/duka_import.py",
        "[Tester]",
        "Expert=ImportDuka\\ImportDukaTicks_EA.ex5",
        "Symbol=EURUSD",
        "Period=M5",
        "Optimization=0",
        "Model=4",                    # 1-minute OHLC for fastest startup
        "FromDate=2026.05.01",
        "ToDate=2026.05.02",
        "ForwardMode=0",
        "Deposit=10000",
        "Currency=USD",
        "ProfitInPips=0",
        "Leverage=500",
        "ExecutionMode=0",
        "OptimizationCriterion=0",
        "Visual=0",
        "ShutdownTerminal=1",
        "",
        "[TesterInputs]",
        f"CustomName={args.custom_name}",
        "CustomPath=Custom\\Dukascopy",
        f'CustomDescr=XAU/USD (Dukascopy historical, imported)',
        f"TickCsvPath={csv_rel}".replace("/", "\\"),
        "SymbolDigits=2",
        "PointSize=0.01",
        "ContractSize=100.0",
        "TickValue=1.0",
        "TickSize=0.01",
        "BaseSpreadPts=30",
        "DeleteFirst=true",
        "",
    ]) + "\r\n"
    write_utf16(ini_path, ini_content)
    print(f"[duka_import] wrote ini  -> {ini_path}")

    # --- 5. Launch tester ------------------------------------------------
    print(f"[duka_import] launching terminal to fire import ...")
    rc = subprocess.call([str(TERMINAL_EXE), f"/config:{ini_path}"])
    print(f"[duka_import] terminal rc={rc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
