"""F0 runner — MT5 Strategy Tester headless launcher for the 5 .set files.

Per the plan (Sprint -1, story F0) at C:/Users/nikof/.claude/plans/have-a-look-at-velvet-marble.md.

Reads a .set file, generates a UTF-16 .ini for MT5's headless tester, launches terminal64.exe,
waits for it to exit, then copies the report into runs/<run_id>/.

Vestigial inputs (RequireAxiBroker, LicenseExpireAt, LicenseCode, SepLic) are filtered out
because the v1.1 EA does not declare them as inputs.

Run with: python scripts/f0_runner.py --set-file "<path>" --run-id <id> --deposit 100000
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path


TERMINAL_EXE = Path(r"C:\Program Files\RoboForex MT5 Terminal\terminal64.exe")
DATA_FOLDER = Path(r"C:\Users\nikof\AppData\Roaming\MetaQuotes\Terminal\5FFA568149E88FCD5B44D926DCFEAA79")
TESTER_PROFILE = DATA_FOLDER / "MQL5" / "Profiles" / "Tester"
REPORTS_DIR = DATA_FOLDER / "MQL5" / "Files"
LOGS_DIR = DATA_FOLDER / "Tester" / "logs"

VESTIGIAL_KEYS = {"RequireAxiBroker", "LicenseExpireAt", "LicenseCode"}


def parse_set_file(set_path: Path) -> dict[str, str]:
    """Read a .set file and return only the primary key=value pairs.

    Skips optimization markers (",F=", ",1=", ",2=", ",3="), section separators,
    and vestigial license fields the EA doesn't actually consume.
    """
    primary: dict[str, str] = {}
    for raw in set_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or "=" not in line:
            continue
        key, _, value = line.partition("=")
        # Skip optimization-mode markers
        if "," in key:
            continue
        # Skip section separators (Sep*, __sec_*__, etc.) and vestigials
        if key.startswith("Sep") or key.startswith("__"):
            continue
        if key in VESTIGIAL_KEYS:
            continue
        primary[key] = value
    return primary


def build_ini(
    inputs: dict[str, str],
    symbol: str,
    period: str,
    from_date: str,
    to_date: str,
    deposit: float,
    leverage: int,
    report_name: str,
    expert_rel_path: str,
    model: int = 0,
) -> str:
    """Build the .ini content (text form before UTF-16 encoding)."""
    lines: list[str] = []
    lines.append("; F0 single-test run, generated by scripts/f0_runner.py")
    lines.append("[Tester]")
    lines.append(f"Expert={expert_rel_path}")
    lines.append(f"Symbol={symbol}")
    lines.append(f"Period={period}")
    lines.append("Optimization=0")
    lines.append(f"Model={model}")  # 0=every real tick, 1=1-min OHLC (faster)
    lines.append(f"FromDate={from_date}")
    lines.append(f"ToDate={to_date}")
    lines.append("ForwardMode=0")
    lines.append(f"Deposit={deposit:g}")
    lines.append("Currency=USD")
    lines.append("ProfitInPips=0")
    lines.append(f"Leverage={leverage}")
    lines.append("ExecutionMode=40")  # 40ms execution delay (close to user's 100ms target)
    lines.append("OptimizationCriterion=0")
    lines.append("Visual=0")
    lines.append(f"Report={report_name}")
    lines.append("ReplaceReport=1")
    lines.append("ShutdownTerminal=1")
    lines.append("")
    lines.append("[TesterInputs]")
    for key, value in inputs.items():
        lines.append(f"{key}={value}")
    return "\r\n".join(lines) + "\r\n"


def write_utf16(path: Path, content: str) -> None:
    """MT5 ini files are UTF-16 LE with BOM."""
    path.write_text(content, encoding="utf-16")


def run_tester(ini_path: Path, run_timeout_sec: int) -> int:
    """Launch terminal64.exe /config:<ini> and wait."""
    cmd = [str(TERMINAL_EXE), f"/config:{ini_path}"]
    print(f"[F0] Launching: {' '.join(cmd)}")
    start = time.time()
    proc = subprocess.Popen(cmd)
    try:
        rc = proc.wait(timeout=run_timeout_sec)
    except subprocess.TimeoutExpired:
        proc.kill()
        print(f"[F0] Tester timeout after {run_timeout_sec}s — killed")
        return -1
    elapsed = time.time() - start
    print(f"[F0] Tester exited rc={rc} after {elapsed:.0f}s")
    return rc


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--set-file", required=True, type=Path, help="Path to .set file")
    ap.add_argument("--run-id", required=True, help="Run identifier (e.g. F0-5k-heavy-grid)")
    ap.add_argument("--symbol", default="XAUUSD")
    ap.add_argument("--period", default="M5")
    ap.add_argument("--model", type=int, default=0, help="Tester model: 0=every real tick, 1=1-min OHLC (faster)")
    ap.add_argument("--from-date", default="2026.01.01")
    ap.add_argument("--to-date", default="2026.05.14")
    ap.add_argument("--deposit", type=float, default=100000)
    ap.add_argument("--leverage", type=int, default=500)
    ap.add_argument(
        "--expert",
        default=r"MoneyDancer_1.1\MoneyDancer_1.1.ex5",
        help="EA path relative to MQL5/Experts/",
    )
    ap.add_argument("--timeout", type=int, default=3600, help="Max seconds per run")
    ap.add_argument("--out-dir", default="runs", help="Output directory (relative to cwd)")
    ap.add_argument(
        "--input-override", action="append", default=[],
        help="Override an EA input: KEY=VALUE. Repeat for multiple. "
             "Applied AFTER reading the .set, so it wins.",
    )
    args = ap.parse_args()

    if not args.set_file.exists():
        print(f"[F0] ERROR: set file not found: {args.set_file}")
        return 2

    inputs = parse_set_file(args.set_file)
    print(f"[F0] Parsed {len(inputs)} inputs from {args.set_file.name}")
    for ov in args.input_override:
        if "=" not in ov:
            print(f"[F0] WARNING: bad --input-override {ov!r}; expected KEY=VALUE")
            continue
        k, v = ov.split("=", 1)
        old = inputs.get(k)
        inputs[k] = v
        print(f"[F0] Override {k}: {old!r} -> {v!r}")

    out_dir = Path(args.out_dir) / args.run_id
    out_dir.mkdir(parents=True, exist_ok=True)

    report_name = f"{args.run_id}-report"
    ini_text = build_ini(
        inputs=inputs,
        symbol=args.symbol,
        period=args.period,
        from_date=args.from_date,
        to_date=args.to_date,
        deposit=args.deposit,
        leverage=args.leverage,
        report_name=report_name,
        expert_rel_path=args.expert,
        model=args.model,
    )
    ini_path = TESTER_PROFILE / f"{args.run_id}.ini"
    write_utf16(ini_path, ini_text)
    print(f"[F0] Wrote ini: {ini_path}")

    rc = run_tester(ini_path, args.timeout)

    # Locate produced report — MT5 writes it to one of several locations depending
    # on build / path style. Empirically confirmed: RoboForex MT5 build 5833 writes
    # Report= name to the data folder root.
    search_dirs = [
        DATA_FOLDER,                                  # confirmed location
        REPORTS_DIR,                                  # MQL5/Files
        DATA_FOLDER / "reports",                      # historical / lowercase
        DATA_FOLDER / "Reports",                      # uppercase variant
        DATA_FOLDER / "MQL5" / "Reports",
        DATA_FOLDER / "Tester" / "Reports",
        TERMINAL_EXE.parent / "Reports",              # install-dir relative
        Path.cwd(),                                   # cwd of subprocess
    ]
    found = []
    for d in search_dirs:
        if not d.exists():
            continue
        for p in d.glob(f"{report_name}*"):
            dest = out_dir / p.name
            shutil.copy2(p, dest)
            found.append(dest)
        # Also try .xml side-cars
        for p in d.glob(f"{report_name}.*"):
            if p.suffix not in (".htm", ".xml", ".html"):
                continue
            dest = out_dir / p.name
            if not dest.exists():
                shutil.copy2(p, dest)
                found.append(dest)

    # Copy tester logs from today
    today_log = LOGS_DIR.glob(f"{time.strftime('%Y%m%d')}.log")
    for log in today_log:
        dest = out_dir / log.name
        shutil.copy2(log, dest)
        found.append(dest)

    print(f"[F0] Run {args.run_id} done. Artifacts:")
    for p in found:
        print(f"  - {p}")
    if not found:
        print("[F0] WARNING: no report artifacts found. Inspect MT5 logs.")
        return 3
    # Save the ini alongside artifacts for traceability
    shutil.copy2(ini_path, out_dir / ini_path.name)
    # Save the source .set
    shutil.copy2(args.set_file, out_dir / args.set_file.name)
    return rc if rc is not None else 0


if __name__ == "__main__":
    sys.exit(main())
