"""Generate Include/NewsCalendar.mqh with calendar events inlined as an array.

Reads data/calendar/2025_full.csv and 2026_full.csv (utc_datetime,currency,tier,label)
and emits MQL5 module with a fixed-size events table + blackout query API.

Times stay in UTC. EA compares against TimeCurrent() which on the imported
XAUUSD.duk_* custom symbols is UTC (the importer writes Duka tick times verbatim).
For live deployment on the real RoboForex server (EET/EEST), a shift would be
needed — out of scope for this sprint.
"""
from __future__ import annotations
import csv
import re
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
SOURCES = [
    ROOT / "data" / "calendar" / "2025_full.csv",
    ROOT / "data" / "calendar" / "2026_full.csv",
]
OUT = ROOT / "mt5" / "1.2" / "MoneyDancer_1.2" / "Include" / "NewsCalendar.mqh"

events = []
for src in SOURCES:
    with src.open() as f:
        for r in csv.DictReader(f):
            iso = r["utc_datetime"]
            # Strip trailing Z and parse
            dt = datetime.strptime(iso.rstrip("Z"), "%Y-%m-%dT%H:%M:%S")
            tier = int(re.sub(r"[^\d]", "", r["tier"]))  # "T1" -> 1
            label = r["label"].replace("\"", "'")
            cur = r["currency"]
            events.append((dt, tier, cur, label))

events.sort()
print(f"Loaded {len(events)} events from {len(SOURCES)} sources")

body = []
body.append("//+------------------------------------------------------------------+")
body.append("//| NewsCalendar.mqh - S1.1 economic-calendar blackout.               |")
body.append("//|                                                                    |")
body.append("//| Loader strategy:                                                   |")
body.append("//|   1. Try MT5's native CalendarValueHistory() for USD/EUR/GBP.     |")
body.append("//|   2. If 0 events come back (tester sandbox may disable it), fall  |")
body.append("//|      back to the hardcoded fallback table generated from          |")
body.append("//|      data/calendar/{2025,2026}_full.csv by                         |")
body.append("//|      scripts/gen_news_calendar_mqh.py.                            |")
body.append("//|                                                                    |")
body.append("//| All times stored as UTC. Compared against TimeCurrent() which on  |")
body.append("//| imported XAUUSD.duk_* custom symbols is UTC (the importer writes  |")
body.append("//| Duka tick times verbatim).                                         |")
body.append("//+------------------------------------------------------------------+")
body.append("#ifndef __MD_NEWSCALENDAR_MQH__")
body.append("#define __MD_NEWSCALENDAR_MQH__")
body.append("")
body.append(f"#define NEWS_FALLBACK_COUNT {len(events)}")
body.append("")
body.append("struct NewsEvent { datetime t; int tier; string cur; string label; };")
body.append("")
body.append("NewsEvent g_news_events[];          // dynamic; sized at News_Init")
body.append("int       g_news_count  = 0;")
body.append("int       g_news_cursor = 0;       // index of next-pending event")
body.append("string    g_news_source = \"none\"; // \"mt5\" or \"fallback\"")
body.append("")
body.append("// ----- helpers -----")
body.append("")
body.append("int News_ImportanceToTier(int imp)")
body.append("{")
body.append("   // ENUM_CALENDAR_EVENT_IMPORTANCE: NONE=0, LOW=1, MODERATE=2, HIGH=3")
body.append("   if(imp >= 3) return 1;  // HIGH -> tier1")
body.append("   if(imp == 2) return 2;  // MODERATE -> tier2")
body.append("   return 3;               // LOW/NONE -> tier3 (we ignore these)")
body.append("}")
body.append("")
body.append("void News_AppendEvent(datetime t, int tier, string cur, string label)")
body.append("{")
body.append("   int n = ArraySize(g_news_events);")
body.append("   ArrayResize(g_news_events, n + 1);")
body.append("   g_news_events[n].t = t;")
body.append("   g_news_events[n].tier = tier;")
body.append("   g_news_events[n].cur = cur;")
body.append("   g_news_events[n].label = label;")
body.append("}")
body.append("")
body.append("void News_SortByTime()")
body.append("{")
body.append("   int n = ArraySize(g_news_events);")
body.append("   for(int i = 1; i < n; i++)")
body.append("   {")
body.append("      NewsEvent key = g_news_events[i];")
body.append("      int j = i - 1;")
body.append("      while(j >= 0 && g_news_events[j].t > key.t)")
body.append("      {")
body.append("         g_news_events[j + 1] = g_news_events[j];")
body.append("         j--;")
body.append("      }")
body.append("      g_news_events[j + 1] = key;")
body.append("   }")
body.append("}")
body.append("")
body.append("// ----- native MT5 calendar loader -----")
body.append("")
body.append("int News_TryLoadFromMT5()")
body.append("{")
body.append("   datetime now = TimeCurrent();")
body.append("   if(now <= 0) return 0;")
body.append("   datetime fromT = now - (datetime)(365 * 86400);")
body.append("   datetime toT   = now + (datetime)(365 * 86400);")
body.append("   string currs[] = {\"USD\", \"EUR\", \"GBP\"};")
body.append("   int total = 0;")
body.append("   for(int c = 0; c < ArraySize(currs); c++)")
body.append("   {")
body.append("      MqlCalendarValue values[];")
body.append("      int n = CalendarValueHistory(values, fromT, toT, \"\", currs[c]);")
body.append("      if(n <= 0) continue;")
body.append("      for(int i = 0; i < n; i++)")
body.append("      {")
body.append("         MqlCalendarEvent ev;")
body.append("         if(!CalendarEventById(values[i].event_id, ev)) continue;")
body.append("         int tier = News_ImportanceToTier((int)ev.importance);")
body.append("         if(tier > 2) continue;  // skip LOW/NONE")
body.append("         News_AppendEvent(values[i].time, tier, currs[c], ev.name);")
body.append("         total++;")
body.append("      }")
body.append("   }")
body.append("   return total;")
body.append("}")
body.append("")
body.append("// ----- hardcoded fallback (generated from data/calendar/{2025,2026}_full.csv) -----")
body.append("")
body.append("void News_LoadFallback()")
body.append("{")
for i, (dt, tier, cur, label) in enumerate(events):
    body.append(
        f'   News_AppendEvent(D\'{dt.strftime("%Y.%m.%d %H:%M")}\', {tier}, "{cur}", "{label}");'
    )
body.append("}")
body.append("")
body.append("void News_Init()")
body.append("{")
body.append("   ArrayResize(g_news_events, 0);")
body.append("   g_news_count  = 0;")
body.append("   g_news_cursor = 0;")
body.append("")
body.append("   int n_mt5 = News_TryLoadFromMT5();")
body.append("   if(n_mt5 > 0)")
body.append("   {")
body.append("      g_news_source = \"mt5\";")
body.append("      g_news_count  = n_mt5;")
body.append("   }")
body.append("   else")
body.append("   {")
body.append("      News_LoadFallback();")
body.append("      g_news_source = \"fallback\";")
body.append("      g_news_count  = ArraySize(g_news_events);")
body.append("   }")
body.append("   News_SortByTime();")
body.append("   PrintFormat(\"[S1.1] NewsCalendar loaded %d events (source=%s)\", g_news_count, g_news_source);")
body.append("}")
body.append("")
body.append("//+------------------------------------------------------------------+")
body.append("//| Is event currency relevant to current symbol?                     |")
body.append("//| XAUUSD reacts to USD; we also include EUR/GBP since they move the |")
body.append("//| dollar index and gold trades against it.                          |")
body.append("//+------------------------------------------------------------------+")
body.append("bool News_RelevantCurrency(string cur)")
body.append("{")
body.append("   if(StringFind(_Symbol, \"XAU\") >= 0) return (cur == \"USD\" || cur == \"EUR\" || cur == \"GBP\");")
body.append("   if(StringLen(_Symbol) >= 6)")
body.append("   {")
body.append("      string left  = StringSubstr(_Symbol, 0, 3);")
body.append("      string right = StringSubstr(_Symbol, 3, 3);")
body.append("      return (cur == left || cur == right);")
body.append("   }")
body.append("   return (StringFind(_Symbol, cur) >= 0);")
body.append("}")
body.append("")
body.append("//+------------------------------------------------------------------+")
body.append("//| Cursor-advance: skip past events older than the post-window.     |")
body.append("//+------------------------------------------------------------------+")
body.append("void News_AdvanceCursor()")
body.append("{")
body.append("   datetime cutoff = TimeCurrent() - (datetime)(NewsBlackoutPostMin * 60);")
body.append("   while(g_news_cursor < g_news_count && g_news_events[g_news_cursor].t < cutoff)")
body.append("      g_news_cursor++;")
body.append("}")
body.append("")
body.append("//+------------------------------------------------------------------+")
body.append("//| True iff a relevant event of allowed tier is within the blackout |")
body.append("//| window [evt - pre, evt + post]. Reads inputs UseNewsBlackout,    |")
body.append("//| NewsBlackoutPreMin, NewsBlackoutPostMin, NewsBlackoutTier2.      |")
body.append("//+------------------------------------------------------------------+")
body.append("bool News_IsBlackoutActive()")
body.append("{")
body.append("   if(!UseNewsBlackout) return false;")
body.append("   News_AdvanceCursor();")
body.append("   datetime now = TimeCurrent();")
body.append("   for(int i = g_news_cursor; i < g_news_count; i++)")
body.append("   {")
body.append("      datetime t = g_news_events[i].t;")
body.append("      if(t > now + (datetime)(NewsBlackoutPreMin * 60)) break;")
body.append("      int tier = g_news_events[i].tier;")
body.append("      bool tierOK = (tier == 1) || (tier == 2 && NewsBlackoutTier2);")
body.append("      if(!tierOK) continue;")
body.append("      if(!News_RelevantCurrency(g_news_events[i].cur)) continue;")
body.append("      if(t > now) return true;                                  // upcoming, within pre-window")
body.append("      if(now - t <= (datetime)(NewsBlackoutPostMin * 60)) return true;  // recently fired")
body.append("   }")
body.append("   return false;")
body.append("}")
body.append("")
body.append("#endif")
body.append("")

OUT.write_text("\n".join(body), encoding="utf-8")
print(f"Wrote {OUT}  ({sum(1 for _ in OUT.open()):,} lines)")
